### PR TITLE
1.3.3 "version"

### PR DESCRIPTION
**Pull request by zvezdochiot**
Library correct version:

4  :  3  :  3
[0]  [1]   [2]
=
[0-2]  [2]  [1]
(4-3) . 3 . 3

### CODE REVIEW

**Comment by hartwork** [comment]
What's the idea? Why does the pull request mass-change PNG files? Thanks!

**Comment by zvezdochiot** [comment]
@hartwork say:
>Why does the pull request mass-change PNG files?

Example?

**Comment by hartwork** [comment]
> Example?

Just open tab "Files changed".

files_changed_Screenshot_20201207_173832

For instance, I see:

files_changed_2_Screenshot_20201207_173919

It would also be nice to to have a description of why LDFLAGS would ideally be changed like that.

**Comment by zvezdochiot** [comment]
@hartwork say:
>For instance, I see:

So you're talking about optimizing/checking images. Yes, it was done.

@hartwork say:
>It would also be nice to to have a description of why LDFLAGS would ideally be changed like that.

Bringing the library numbering to the standard form.

**Comment by hartwork** [comment]
> So you're talking about optimizing/checking images. Yes, it was done.

Seems unrelated to versioning to me. Why put that in the same pull request?


> Bringing the library numbering to the standard form.

Could you elaborate what problems you see with the old for, why the new form is the best choice, and how this change will affect backwards compatibility with previous releases?

**Comment by zvezdochiot** [comment]
@hartwork say:
>Could you elaborate what problems you see with the old form

When updating a library to a new release, for example 1.3.4, in your version you will have to rebuild all software that uses it. In my case, no.

**Comment by hartwork** [comment]
> When updating a library to a new release, for example 1.3.4, in your version you will have to rebuild all software that uses it. In my case, no.

I do have a bit of background with soname versioning; let me have a closer look:

## Before (i.e. without your patch)

```console
# LD_LIBRARY_PATH=.libs lddtree .libs/imagew | fgrep worsener
    libimageworsener-1.3.3.so => .libs/libimageworsener-1.3.3.so

# find -name \*.so\* -exec ls -l {} +
-rwxr-xr-x 1 user user 667440 Dez  7 20:42 ./.libs/libimageworsener-1.3.3.so
lrwxrwxrwx 1 user user     25 Dez  7 20:42 ./.libs/libimageworsener.so -> libimageworsener-1.3.3.so
```


## After

```console
# LD_LIBRARY_PATH=.libs lddtree .libs/imagew | fgrep worsener
    libimageworsener.so.1 => .libs/libimageworsener.so.1

# find -name \*.so\* -exec ls -l {} +
lrwxrwxrwx 1 user user     25 Dez  7 20:36 ./.libs/libimageworsener.so -> libimageworsener.so.1.3.3
lrwxrwxrwx 1 user user     25 Dez  7 20:36 ./.libs/libimageworsener.so.1 -> libimageworsener.so.1.3.3
-rwxr-xr-x 1 user user 667440 Dez  7 20:36 ./.libs/libimageworsener.so.1.3.3
```

I agree that the old state looks unusual and that the app binary linking to the `-1.3.3.so` rather than a `.so.1` symlink seems suboptimal.

I checked the math now; if the idea is to replace the current version 1.3.3 into the soname, the numbers look right:
```
   1.3.3 = <c>-<a>.<a>.<r>  # c = current, a = age, r = revision
-> r = 3, a = 3, c - a = 1
-> r = 3, a = 3, c - 3 = 1
-> r = 3, a = 3, c = 4
-> -version-info 4:3:3
```

Why add `-no-undefined`? Can that be dropped as unrelated or why is it necessary?

If you can drop/extract the image mass-changes as well I believe this is close to be presentable to Jason.

**Comment by zvezdochiot** [comment]
@hartwork say:
>Why add -no-undefined? Can that be dropped as unrelated or why is it necessary?

Without this, symlinks will not be processed.

@hartwork say:
>If you can drop/extract the image mass-changes as well I believe this is close to be presentable to Jason.

I gave you a recipe. No more. I myself use it. What you do is up to you.

**Comment by hartwork** [comment]
> > Why add -no-undefined? Can that be dropped as unrelated or why is it necessary?
> 
> Without this, symlinks will not be processed.

Given it's name "no-undefined" that sounds unlikely, no? Have you checked `man ld`?
Also, it's `--no-undefined` with double dashes:
```
# man ld | grep -oE -- -+no-undefined | sort -u
--no-undefined
```

> I gave you a recipe. No more. I myself use it. What you do is up to you.

I'm a visitor here so I don't take that personal but I think the imageworsener project deserves more respect and proper pull requests, proper bug reports with well-separated self-explaining commits and a helpful description and so on. There's probably a reason the was no reply here close to two years before me today. So you don't want to clean the pull request up to have an actual chance to be merged and have actual benefit to the community and record a proper contribution in your name?

**Comment by zvezdochiot** [comment]
@hartwork say:
>So you don't want to clean the pull request up to have an actual chance to be merged and have actual benefit to the community and record a proper contribution in your name?

I didn't add a single line of code, I didn't even poke around in it! This PR is just a recipe for getting a good library into shape. But I'm not going to get into the project itself, it is necessary to delve into the code.

**Comment by hartwork** [comment]
Getting the unrelated changes out of here does not need delving into code.

**Comment by zvezdochiot** [comment]
@hartwork say:
>Getting the unrelated changes out of here does not need delving into code.

I will not change anything for myself. All the changes that I made I need.

**Comment by hartwork** [comment]
Okay, then my work here is done. What a waste of time.

**Comment by jsummers** [comment]
A few comments. I was aware that "la_LDFLAGS=-release" breaks compatibility. It was intentional, though maybe not for all the best reasons.

I got discouraged by the increasing messiness of this program. I don't remember what all the problems were, but I didn't feel like I was able to assess its compatibility with previous version, and the division of duties (or lack thereof) between the command-line tool and the library is a total mess.

I'll try to do at least a little bit of maintenance in the near future. Maybe move the regression tests to a separate project. But I haven't decided what to do about the library version.

**Comment by hartwork** [comment]
> I got discouraged by the increasing messiness of this program. I don't remember what all the problems were, but I didn't feel like I was able to assess its compatibility with previous version, and the division of duties (or lack thereof) between the command-line tool and the library is a total mess.

If you're looking for someone to do Jitsi-based refactoring discussions with, please find me off-GitHub as needed. Just an idea, totally okay to ignore.

> Maybe move the regression tests to a separate project.

What would be the benefit of moving the regression tests elsewhere? Having them close sounds like a good choice, especially when adding continues integration (e.g. based on GitHub Actions) in the near future.

> But I haven't decided what to do about the library version.

I think there is two different pair of shoes here:
- On is use of `-release` versus `-version-info`
- The other is what values to use, what guarantees to make.

I'm trying to say that just because you start using `-version-info` you don't need to make more guarantees about compatibility as previously. If you make a new release and you're unsure about backwards-compatibility then `-version-info C:R:A` becomes `-version-info <C+1>:0:0` — that's not providing more guarantees (see https://verbump.de/). @jsummers does that make sense?

**Comment by zvezdochiot** [comment]
⚠️ Not resolved !!!

**Pull request closed without merging**
